### ISSUE TITLE
Application status

### ISSUE THREAD

**Issue by konryd** [kubernetes-sigs/application#11]
The Application resource is intended to be used by UIs. One of the most useful features of those is reporting the health of the displayed resources.

The "status" of the application (for the sake of discussion, let's simplify to either "OK" or "Error") can be generated in one of the following ways:
1. With an explicit field in ApplicationStatus.
1. With a reference to a a running pod's readiness probe.
1. By analyzing Kubernetes-level events involving the application.
1. By computing status of each of the Application's components and using the most problematic one.

Each of the approaches carries some trade-offs:

### Explicit field in ApplicationStatus
Pros:
1. Easy to consume.

Cons:
1. Would have to be populated by the application controller, the logic that would run there is far from obvious and might differ depending on application

### With a reference to a a running pod's readiness probe.
Pros:
1. Easy to consume.
1. Easy to implement custom status logic.
1. The pod to use might be one that already runs inside the app (eg. the worpress app might use the serving pod for this, which would also check the database)

Cons:
1. The pod would have to be managed with a deployment, growing the overhead for each application.
1. The application owners / providers would have to include the readiness pod.
1. Puts additional load on cluster resources.

NOTE: this could be an optional approach, with a default fallback being any of the other approaches.

### By analyzing Kubernetes-level events
Pros:
1. Implementable using only existing Kubernetes mechanism.
1. Similar approach works well for existing resources ([eg. Deployment in kube-dashboard](https://github.com/kubernetes/dashboard/blob/3988cad30bba696e1382159e6e00a64ec1bf298c/src/app/backend/resource/deployment/list.go#L137))

Cons:
1. The algorithm for changing a list of events into a status would have to wear out in use and will be easy to break, especially in the initial period until the Application resource matures.
1. Most likely, will only be able to capture the Kubernetes-control-plane-level problems. Making it work for individual component's statuses as well will inherit all of the other solutions' problems.
1. Will force each consumer to re-implement the status computation logic.

### By computing status of each of the Application's components and using the most problematic one
Pros:
1. Exhaustive and very likely to match users' expectations.

Cons:
1. Expensive to compute, even more so when listing all applications in cluster (where it would pretty much mean querying for all available GroupKinds everywhere).

**Comment by konryd** [comment]
> events are not a good way to determine current state. They can be lost, and they can conflict, and they are not required to be delivered or emitted
Aren't these worries theoretical? The events are used to generate pod's status eg. in Kubernetes Dashboard. I am not not aware of users complaining.

> What if the App controller were responsible for listing all the "top-level objects" that match the App in the App's .status
That would be convenient for listing a single app's components, and their statuses, but for computing the aggregate status of the application it will be comparable to the current solution, especially when computing statuses for all applications (we'll end up with API calls covering all individual resources, which might end up spanning most of the cluster).

**Comment by prydonius** [comment]
I'm curious about how people use healthchecks to determine healthiness in the context of an application today. I would imagine a lot of simpler applications (e.g. ones we have Helm charts for today) would only need a single health check for the main services. For example, in WordPress this would be the WordPress deployment and the MySQL deployment. It may even be enough in this case to just check the health of the WordPress deployment as it should fail if it cannot connect to MySQL. I think it's good practice for a service to have a healthcheck endpoint that checks that it can successfully connect to dependent services.

It'd be helpful for me to see examples of the more complex applications/architectures that use an extra service to provide an aggregate healthcheck for the application, or would require many healthchecks for each individual component.

**Comment by konryd** [comment]
@prydonius I like the idea of using health checks. Do you have thoughts on the exact implementation? What do you think about making it a service reference in the style of #12 plus some fields for homing down no the exact port/path?

**Comment by prydonius** [comment]
@konryd would it not be easier to use workload references (I believe just these five: Deployment, StatefulSet, ReplicaSet, DaemonSet, Pod) as we can leverage the readiness/liveness checks that these already do. Now that I think about it, this also gives app devs quite a lot of flexibility to decide whether they want to aggregate healthchecks across different services they've deployed, or deploy a single healthcheck service to compute the aggregated health.

For example, in WordPress I would just point to the WordPress Deployment as this covers the database connection too. For a more complex app, I could opt to bundle a separate Pod/Deployment to reduce the overhead of querying every workload in the app bundle.

This all assumes that we only need to check the health of an app's workloads. Are there other resource types that would make sense to check? PVCs/PVs, ConfigMaps, Secrets would all be part of workload readiness (the pods won't start if these aren't bound/don't exist). A LoadBalancer-type Service might not be accessible whilst the cloud provider provisions an IP/hostname, so there may be a need to check Services as you suggested (but for this case we may just be able to check for type: LoadBalancer and if an IP/hostname has been assigned). Anything else I could be missing?

**Comment by lwander** [comment]
> The Application resource is intended to be used by UIs. One of the most useful features of those is reporting the health of the displayed resources.

Is reporting the health meant for human consumers in a UI, programmatic consumers via the API, or some combination of both?

If you're leaning more toward the former, I don't know if a single "OK" vs. "Error" is necessary, or even enough. Like @prydonius points out there's a large set of resources (not even counting CRDs) that might be worth rolling up into application health. If we want to provide users with a quick look into the status of their application, maybe the UI should surface each resource's health individually rather than try and guess at the overall status. This can include aggregating pod states, health checks, events, etc... all into your application dashboard.

On the programmatic side, coming up with a top-level heuristic can be very tricky. What if your pods fail their readiness probes a few times before coming online? Any application status that depends on this will flap between "OK" and "Error" each time you do a deployment. Furthermore, you might have more sophisticated notions of health built into your metrics/monitoring system that aren't natively exposed to the Kubernetes API, making it tricky for the application CRD to infer anything about your apps status. For example, you might be monitoring some internal queue depth & when a certain threshold is exceeded you don't want to mark you pods as unhealthy (now no requests are processed), you want to page an SRE or scale up your deployments.

I'm pointing this out because we'd like to take advantage of this CRD in Spinnaker, which has its own notion of applications. The view surfaced to an operator gives quite a bit of detail about what's going on in your cluster, without trying roll status up into a top-level object. Take for example this one pod that won't be scheduled in this application:

![50p9y6ud48v](https://user-images.githubusercontent.com/4874941/38560869-a64eafa4-3ca4-11e8-9be4-25502a185380.png)

**Comment by konryd** [comment]
@prydonius I started with just services to avoid the need to re-implement their round-robin semantics, but I'm not against referencing workloads directly - nice thing about this is it wouldn't require adding a service just for the health check.

As for the unprovisioned LB case - this can't be detected with a blackbox approach (==healthcheck)  from inside the cluster, which gets us back to testing components (or only services) one-by-one, which - as @lwander says, is often more appropriate to do on the client side / ui.

**Comment by konryd** [comment]
@lwander I think the status should be helpful in both cases: lightweight, glanceable status for humans and some reasonable check for automated tools (eg. testers). It doesn't need to provide all of this on the API level, though.

I'd like to focus on items that require some input from user and thus benefits from standardization in a CRD: Querying each component one-by-one is something that clients can do (and proceed as they wish: either roll up or display in full), selecting an individual healthcheck to represent the health of a whole app requires human input.
