### ISSUE TITLE
 Resource, Component or Object ?

### ISSUE THREAD

**Issue by barry8schneider** [kubernetes-sigs/application#31]
The readme makes several references to Application resources or components in the cluster

* The Application CRD provides a way for you to aggregate individual Kubernetes components
* allows for the aggregation and display of all the components in the Application.
* The selector is used to match resources that belong to the Application. 
* All of the applications resources should be labels such that they match this selector. 
* Users should use the app.kubernetes.io/name label on all components of the Application 

In the Kubernetes documentation, the only reference to [components](https://kubernetes.io/docs/concepts/overview/components/) is related to the binary components needed to deliver a functioning Kubernetes cluster.

In the Kubernetes documentation, a [resource ](https://kubernetes.io/docs/concepts/api-extension/custom-resources/#custom-resources )is defined as "A resource is an endpoint in the Kubernetes API that stores a collection of API objects of a certain kind."

I would like to propose that we try to use Kubernetes terminology as much as possible, 

Should the readme examples listed above for components and resources be documented as objects (Kubernete Objects)?

**Comment by kow3ns** [comment]
We should probably reference Kinds instead of resources as you point out, and componentKinds  really identifies resources. I don't think we need to disambiguate between cluster components and application components though. Manifests, and any other system, can be composed of components. I don't think components, even in the space of Kubernetes, is a reserved word that is applicable only to the cluster.
