### ISSUE TITLE
Application Resource Generation

### ISSUE THREAD

**Issue by dlorenc** [kubernetes-sigs/application#43]
Is tooling for generating Application resources (maybe from a set of YAMLs or something similar) in-scope for this project?

Ref https://github.com/kubernetes-sigs/kustomize/issues/23

**Comment by prydonius** [comment]
My 2 pence is that generating the Application resource is better left to the deployment tools (e.g. Helm, kustomize, ksonnet). Especially since some of these tools represent some of the application metadata in different ways, such as Helm's Chart.yaml, and it wouldn't make sense to have that knowledge in this project.
